spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    show-sql: true

  application:
    name: irrigation-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmsalah.elsayed@gmail.com
    password: l2032280
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

alert:
  recipient:
    email: ahmed55salah66@gmail.com

server:
  servlet:
    context-path: /irrigation
  port: 8089
