spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format:
          sql: 'true'
        default_schema: irrigation
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  application:
    name: irrigation-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: root


server:
  servlet:
    contextPath: /irrigation
  port: 8089


